### ISSUE TITLE
Apply logo image on main page 

### ISSUE THREAD

**Issue by moreal** [planetarium/www.nine-chronicles.dev#5]
## Work items

Please apply logo image on the main page. You can specify logo image by setting `hero.image` field for each `index.md`. You can see the `hero`'s spec at https://vitepress.dev/reference/default-theme-home-page#hero-section.

```yaml
...
hero:
  name: Nine Chronicles
  text: Developer Portal
  tagline: Build your Nine Chronicles
  image: <url>
...
```

You should use https://github.com/planetarium/9c-launcher/raw/development/src/main/resources/logo.png as logo

![logo](https://github.com/planetarium/9c-launcher/raw/development/src/main/resources/logo.png)

### AS-IS

![image](https://github.com/user-attachments/assets/1a41bb19-4619-49ad-bcb1-f149b4aacbd6)

### TO-BE

![image](https://github.com/user-attachments/assets/785fd60a-2274-45b7-9a7b-770246ab913b)
